In [2]:
import cv2 # opencv读取的格式是BGR，与matplotlib不同
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [6]:
pic_path = '/Users/xiaoziqi/Desktop/Code/deep-learning/OpenCV/data/cat1.jpeg'
img = cv2.imread(pic_path)

In [3]:
img

array([[[ 38,  36,  42],
        [ 38,  36,  42],
        [ 37,  35,  41],
        ...,
        [ 61,  78,  99],
        [ 60,  76,  99],
        [ 61,  77, 100]],

       [[ 38,  36,  42],
        [ 38,  36,  42],
        [ 38,  36,  42],
        ...,
        [ 62,  79, 100],
        [ 62,  78, 101],
        [ 63,  79, 102]],

       [[ 39,  37,  43],
        [ 39,  37,  43],
        [ 39,  37,  43],
        ...,
        [ 61,  78,  99],
        [ 60,  77,  98],
        [ 61,  78,  99]],

       ...,

       [[ 42,  40,  46],
        [ 42,  40,  46],
        [ 42,  38,  44],
        ...,
        [ 92,  98, 111],
        [ 90,  96, 109],
        [ 85,  93, 106]],

       [[ 43,  41,  47],
        [ 44,  42,  48],
        [ 42,  38,  44],
        ...,
        [111, 119, 132],
        [100, 108, 121],
        [ 78,  86,  99]],

       [[ 45,  41,  47],
        [ 47,  43,  49],
        [ 45,  38,  45],
        ...,
        [116, 124, 137],
        [112, 119, 134],
        [ 83,  92, 106]]

In [4]:
# 图像的显示，也可以创建多个窗口
cv2.imshow('image', img)
# 等待时间，毫秒级，0表示任意键终止
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img.shape

(301, 320, 3)

In [7]:
img_gray = cv2.imread(pic_path, cv2.IMREAD_GRAYSCALE)
img_gray

array([[ 38,  38,  37, ...,  82,  81,  82],
       [ 38,  38,  38, ...,  83,  83,  84],
       [ 39,  39,  39, ...,  82,  81,  82],
       ...,
       [ 42,  42,  40, ..., 101,  99,  96],
       [ 43,  44,  40, ..., 122, 111,  89],
       [ 43,  45,  41, ..., 127, 123,  95]], dtype=uint8)

In [8]:
img_gray.shape

(301, 320)

In [1]:
# 图像的显示，也可以创建多个窗口
cv2.imshow('image', img_gray)
# 等待时间，毫秒级，0表示任意键终止
cv2.waitKey(500)
cv2.destroyAllWindows()

NameError: name 'cv2' is not defined

In [ ]:
cv2.imwrite('data/my_cat.jpeg', img_gray)

### 数据读取-视频

- cv2.VideoCapture可以捕获摄像头，用数字来控制不同的设备，例如0，1.
- 如果是视频文件，直接指定好路径即可。

In [3]:
vc = cv2.VideoCapture('data/test.mp4')

In [6]:
# 检查打开是否正确
if vc.isOpened():
    is_open, frame =  vc.read()
else:
    is_open = False
is_open

array([[[253, 253, 253],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [253, 253, 253]],

       [[253, 253, 253],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [253, 253, 253]],

       [[253, 253, 253],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [253, 253, 253]],

       ...,

       [[253, 253, 253],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [253, 253, 253]],

       [[253, 253, 253],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [253, 253, 253]],

       [[253, 253, 253],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [253, 253, 253]]

In [ ]:
while open:
    ret, frame = vc.read()
    if frame is None:
        break
    if ret:
        v_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow('result', v_gray)
        if cv2.waitKey(10) & 0xFF == 27:
            break
vc.release()
cv2.destroyAllWindows()

In [ ]:
vc = cv2.VideoCapture(0)
while(True):
    # 读取一帧，read()方法是其他两个类方法的结合，具体文档
    # ret为bool类型，指示是否成功读取这一帧
    ret, frame = vc.read()
    # 就是个处理一帧的例子，这里转为灰度图
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # 不断显示一帧，就成视频了
    # 这里没有提前创建窗口，所以默认创建的窗口不可调整大小
    # 可提前使用cv.WINDOW_NORMAL标签创建个窗口
    cv2.imshow('frame',gray)
    # 若没有按下q键，则每1毫秒显示一帧
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 所有操作结束后不要忘记释放
vc.release()
cv2.destroyAllWindows()